import type { LandingPage } from "./landing-pages";

export const casablancaSeo: LandingPage = {
  path: "/casablanca/seo",
  lang: "fr",
  title: "Consultant SEO Casablanca | Audit & Référencement Naturel",
  description: "Consultant SEO à Casablanca : audit technique, contenu, référencement local et corrections web. Un plan priorisé et un suivi avec Search Console.",
  eyebrow: "Casablanca · SEO technique et local",
  h1: "Consultant SEO à Casablanca : audit et référencement naturel",
  intro: "Votre site existe, mais vos pages attirent peu de visiteurs depuis Google ? Je vous aide à distinguer les problèmes d’indexation, de contenu et de performance, puis à mettre en œuvre les corrections utiles. Vous échangez directement avec Soufiane Boutatss, développeur web freelance au Maroc.",
  market: "Casablanca, Maroc",
  projectSlugs: [],
  updatedAt: "2026-10-05",
  sections: [
    { title: "Un diagnostic à partir de vos pages et de vos recherches", paragraphs: ["L’audit commence par les pages qui présentent vos prestations et les recherches sur lesquelles elles apparaissent déjà. Search Console permet d’observer les impressions, les clics et les positions par page et par requête. Nous distinguons les recherches sur votre nom des recherches sur vos services.", "Une page non indexée demande une vérification différente d’une page visible en position 40. Avant de réécrire un titre ou d’ajouter du texte, nous contrôlons le code HTTP, le canonical, les éventuels blocages et le contenu que Google peut consulter."], items: ["Inspection des pages prioritaires", "Requêtes commerciales et de marque", "Pages indexées et exclues", "Diagnostic avant correction"] },
    { title: "Audit SEO technique et corrections sur votre site", paragraphs: ["Les contrôles portent sur robots.txt, le sitemap, les redirections, les liens internes et les métadonnées. Pour un site React ou Next.js, nous examinons aussi le rendu des contenus publics et les éléments qui dépendent du JavaScript.", "Les recommandations indiquent l’URL, le problème, la correction proposée et le contrôle à réaliser après publication. Selon le devis, je peux intervenir dans le code ou transmettre un plan de travail à votre équipe. Les mesures mobiles permettent de prioriser les problèmes de chargement et d’interaction observés."], items: ["Indexabilité et redirections", "Canonical et langues", "Titres et contenu rendu", "Performance mobile mesurée"] },
    { title: "Référencement local : décrire votre activité réelle à Casablanca", paragraphs: ["Un site local doit rendre votre activité identifiable : prestations, coordonnées, zone réellement desservie et moyens de contact. Les pages de services expliquent ce que le client peut demander et présentent des exemples pertinents, plutôt que répéter un nom de ville dans chaque paragraphe.", "Si votre activité est éligible à Google Business Profile, la fiche et le site doivent fournir des informations cohérentes. L’adresse, les horaires et les avis doivent refléter la réalité de votre entreprise. L’éligibilité et les accès à la fiche sont vérifiés avant toute intervention."], items: ["Prestations et zone desservie", "Coordonnées cohérentes", "Pages locales utiles", "Fiche d’établissement si éligible"] },
    { title: "Des contenus qui aident à choisir votre prestation", paragraphs: ["Chaque page commerciale répond à une intention principale : comprendre un service, examiner une réalisation ou demander un devis. Nous précisons les livrables, les limites, les étapes et les informations nécessaires au client pour prendre sa décision.", "Les articles répondent aux questions de préparation et renvoient vers le service correspondant. Lorsque plusieurs pages proposent presque la même réponse, nous examinons leurs contenus et leurs résultats avant de choisir une différenciation ou une consolidation."], items: ["Une intention principale par page", "Explications et preuves pertinentes", "Liens entre guides et services", "Analyse des pages similaires"] },
    { title: "Ce que vous recevez et comment suivre les résultats", paragraphs: ["Le périmètre de l’audit définit les pages examinées, les accès nécessaires et les livrables. Le plan d’action classe les corrections par impact et effort ; il distingue les problèmes bloquants des améliorations à tester ensuite.", "Après publication, nous vérifions les pages modifiées et comparons des périodes de durée égale dans Search Console. Le suivi porte sur les mêmes pages, requêtes et pays, ainsi que sur les demandes de contact lorsqu’elles sont mesurées. Une hausse des impressions ne constitue pas, à elle seule, une hausse des clients."], items: ["Rapport avec URLs concernées", "Corrections classées par priorité", "Vérification après publication", "Suivi des pages et des demandes"] },
    { title: "Consultant freelance ou agence SEO : quel accompagnement choisir ?", paragraphs: ["Un consultant freelance convient à un travail cadré où vous souhaitez échanger avec la personne qui analyse et corrige le site. Une agence peut être adaptée si vous avez besoin de plusieurs spécialistes ou d’une production continue sur un volume important de contenus.", "Mon intervention associe développement web et SEO technique. Les besoins dépassant le périmètre convenu, comme une production éditoriale importante ou une campagne de relations presse, sont identifiés séparément. Le budget dépend des pages, de l’état du site et des corrections attendues."], items: ["Interlocuteur direct", "Audit ou implémentation", "Périmètre de contenu défini", "Devis selon l’existant"] },
  ],
  faqs: [
    { question: "Combien coûte un audit SEO à Casablanca ?", answer: "Le budget dépend du nombre de pages, des langues, de la technologie et de la profondeur des vérifications. Envoyez l’URL de votre site et vos objectifs : le devis distingue l’audit, les corrections et le suivi." },
    { question: "Êtes-vous une agence SEO à Casablanca ?", answer: "Je suis un développeur web freelance proposant un accompagnement SEO technique et des corrections sur le site. Vous échangez directement avec moi. Si le projet demande une équipe plus large, nous le précisons au cadrage." },
    { question: "Pourquoi mon site est-il indexé mais mal positionné ?", answer: "L’indexation rend une page disponible pour la recherche ; elle ne garantit pas une bonne position. Il faut examiner l’intention de recherche, le contenu, les pages concurrentes, les liens et la présentation du service pour comprendre les améliorations possibles." },
    { question: "Pouvez-vous garantir le top 10 sur Google ?", answer: "Non. Aucune correction du site ne permet de garantir une position. La mission vise des pages utiles, une meilleure compréhension du site et un suivi mesurable. La concurrence et les décisions de Google restent hors de notre contrôle." },
    { question: "Au bout de combien de temps les changements sont-ils visibles ?", answer: "Google doit d’abord explorer et réévaluer les pages. Le délai varie selon le site, les changements et la concurrence. Nous contrôlons la publication et l’exploration, puis observons les résultats sur plusieurs périodes comparables sans promettre de date de classement." },
    { question: "Quels accès faut-il fournir ?", answer: "L’URL du site et un accès adapté à Search Console permettent de commencer. L’implémentation peut demander des accès au code, au CMS ou à l’hébergement, limités aux besoins de la mission et partagés par un canal approprié." },
  ],
  related: [
    { href: "/blog/seo-site-entreprise-maroc", label: "Guide : comprendre la visibilité d’un site d’entreprise" },
    { href: "/creation-site-web-casablanca", label: "Créer ou refondre votre site à Casablanca" },
    { href: "/seo", label: "Audit technique et performance web" },
    { href: "/a-propos", label: "Le parcours de Soufiane Boutatss" },
  ],
};
