import type { LandingPage } from "./landing-pages";

type RegionalContent = Pick<LandingPage, "sections" | "faqs" | "related"> & { projectSlugs: string[] };

// Regional routes retain their URLs, but explain specific project decisions
// instead of swapping a country name in an otherwise identical page.
export const regionalContent: Record<string, RegionalContent> = {
  "/france/creation-site-web": {
    sections: [
      { title: "Présenter vos services à une clientèle française", paragraphs: ["Pour une entreprise de services, le site doit rendre l’offre compréhensible avant la prise de contact : prestations, zone réellement desservie, exemples et informations pour préparer une demande. Nous organisons les pages autour de ces questions plutôt qu’autour d’une liste de technologies.", "Un portfolio comme Reby Art montre une autre priorité : laisser les œuvres guider la visite. Le type de site, les images et l’autonomie de publication sont donc discutés avant de retenir un CMS ou une interface React."], items: ["Pages de prestations", "Réalisations pertinentes", "Contact et demande de devis", "Autonomie de publication"] },
      { title: "Préparer une création ou une refonte à distance", paragraphs: ["Les maquettes et les textes sont validés en français, avec un responsable identifié pour chaque contenu. Avant une refonte, nous inventorions les anciennes adresses et les pages déjà visitées afin de préparer des redirections vers les pages correspondantes.", "Le dossier de livraison précise les accès, le domaine, l’hébergement et la procédure de mise à jour. Le devis distingue ce qui est fourni par votre entreprise de ce qui fait partie de la mission de développement."], items: ["Textes et images validés", "Inventaire des URLs", "Recette mobile", "Accès et prise en main"] },
    ],
    faqs: [{ question: "Dois-je être disponible à chaque étape ?", answer: "Un référent doit valider la structure, les maquettes et les contenus. Les décisions peuvent être regroupées lors de points planifiés ; le travail ne nécessite pas une présence continue." }, { question: "Puis-je conserver mon domaine actuel ?", answer: "Oui, si vous disposez des accès nécessaires. Le déploiement est préparé avec le domaine et l’hébergement retenus, en préservant les services associés comme votre messagerie." }],
    projectSlugs: ["pizza-napoli-toul", "reby-art", "horea-formation"],
    related: [{ href: "/portfolio/reby-art", label: "Portfolio React pour un peintre français" }, { href: "/france", label: "Collaboration avec les entreprises françaises" }, { href: "/creation-site-web", label: "Choisir le périmètre d’un site" }],
  },
  "/canada/creation-site-web": {
    sections: [
      { title: "Un site francophone ou bilingue selon votre audience", paragraphs: ["Un site destiné au Québec et un site visant plusieurs provinces peuvent avoir des besoins linguistiques différents. Nous commençons par les publics à atteindre et les contenus disponibles pour décider des versions française et anglaise.", "Chaque version doit disposer de pages, de titres et d’un parcours de contact cohérents. Une simple traduction du menu ne remplace pas la traduction des prestations, des confirmations de formulaire et des informations utiles au visiteur."], items: ["Publics et langues", "Contenus validés par version", "URLs linguistiques distinctes", "Formulaires et confirmations"] },
      { title: "Organiser les contenus et les validations depuis le Canada", paragraphs: ["HighUp Counselling, un site canadien présenté dans le portfolio, illustre une vitrine de services réalisée avec Wix. Le choix d’une solution dépend ici de la présentation de l’offre et de la capacité à gérer les contenus ; un développement sur mesure n’est pas nécessaire pour tous les sites.", "Les points de validation sont planifiés dans des plages horaires communes. Pour un commerce en ligne, la devise, les territoires de livraison et les intégrations sont définis séparément du site vitrine afin de ne pas masquer un périmètre plus important."], items: ["Choix CMS ou sur-mesure", "Référent pour les contenus", "Réunions planifiées", "Devise et livraison si e-commerce"] },
    ],
    faqs: [{ question: "Un site bilingue double-t-il le travail ?", answer: "Les composants peuvent être partagés, mais chaque langue demande des contenus, des validations et des vérifications de navigation. Le devis précise les pages et fonctions disponibles dans chaque version." }, { question: "Comment valider le site avec un décalage horaire ?", answer: "Les retours sont regroupés dans un document partagé, avec des démonstrations et des réunions planifiées. Les heures de disponibilité sont convenues avant de commencer." }],
    projectSlugs: ["highup-counselling"],
    related: [{ href: "/portfolio/highup-counselling", label: "HighUp Counselling : site canadien de services" }, { href: "/canada", label: "Développement pour le Canada et le Québec" }, { href: "/creation-site-web", label: "Préparer un projet de site" }],
  },
  "/france/developpeur-react": {
    sections: [
      { title: "Renfort React pour une équipe ou une agence française", paragraphs: ["La mission peut prendre la forme d’une intégration de maquettes, d’un nouveau parcours ou d’une reprise de composants. Avant de chiffrer, je consulte les conventions du dépôt, les tickets, la documentation API et les conditions de déploiement.", "Pour une agence, les limites de la mission sont définies avec votre chef de projet : écrans à réaliser, états à couvrir, tests attendus et modalités de revue. Le code est livré dans votre workflow, avec des changements suffisamment petits pour être examinés."], items: ["Intégration de maquettes", "API existante", "Revues de code", "Livraisons par parcours"] },
      { title: "React pour un site public : le cas d’un portfolio", paragraphs: ["Reby Art est un portfolio React destiné à présenter un peintre français. Son contexte montre l’intérêt d’une navigation qui donne une place centrale aux œuvres et d’une interface adaptée au contenu visuel.", "Pour votre site, la mission examine les images, les écrans mobiles et l’accès aux contenus depuis une URL directe. Si l’acquisition Google est prioritaire, nous vérifions aussi le HTML fourni au moteur et le besoin d’un rendu serveur."], items: ["Navigation des galeries", "Images et affichage mobile", "URLs partageables", "Rendu des contenus publics"] },
    ],
    faqs: [{ question: "Pouvez-vous suivre les conventions de mon équipe React ?", answer: "Oui. Les conventions de composants, de branches et de validation sont examinées au démarrage. Une première livraison permet de vérifier l’intégration dans votre workflow." }, { question: "Travaillez-vous uniquement sur de nouveaux projets ?", answer: "Non. Une mission peut porter sur un parcours, une migration ciblée ou la correction d’un frontend existant, après audit du dépôt et des dépendances." }],
    projectSlugs: ["reby-art"],
    related: [{ href: "/portfolio/reby-art", label: "Étude de cas React : Reby Art" }, { href: "/france/developpeur-nextjs", label: "Next.js pour les pages publiques" }, { href: "/developpeur-react", label: "Architecture et intégration React" }],
  },
  "/canada/developpeur-react": {
    sections: [
      { title: "Préparer une interface React en français et en anglais", paragraphs: ["Pour un produit visant des utilisateurs francophones et anglophones, la traduction concerne aussi les formulaires, les erreurs et les libellés issus de l’API. Les formats de date, les montants et les textes longs sont vérifiés dans les deux langues.", "La séparation des textes et des composants facilite les validations. Les versions publiques doivent posséder des URLs et des métadonnées distinctes ; les préférences d’un espace privé peuvent, elles, être gérées dans le compte utilisateur."], items: ["Messages d’erreur traduits", "Formats et textes longs", "Contenus séparés des composants", "Versions publiques ou espace privé"] },
      { title: "Des livraisons adaptées à une équipe au Canada", paragraphs: ["Le décalage horaire conduit à documenter les décisions et les questions bloquantes. Une livraison comprend le parcours concerné, les conditions de test et les points qui demandent une validation, pour que votre équipe puisse l’examiner sans attendre un appel.", "La connexion à votre API est cadrée avec ses états de chargement, ses erreurs et ses permissions. Si une donnée manque ou si le réseau devient indisponible, l’interface doit expliquer l’état plutôt que présenter un écran qui semble fonctionner."], items: ["Démonstrations et notes de livraison", "Créneaux de revue convenus", "Contrats API", "Tests des états réseau"] },
    ],
    faqs: [{ question: "Pouvez-vous intervenir sur un produit React bilingue ?", answer: "Oui. Le périmètre précise les écrans, les traductions disponibles, les formats et les personnes chargées de valider chaque langue. Les traductions métier doivent être fournies ou approuvées par votre équipe." }, { question: "Êtes-vous installé au Canada ?", answer: "Non. Le développement est réalisé à distance depuis le Maroc. La collaboration prévoit des plages de disponibilité communes et un suivi écrit." }],
    projectSlugs: [],
    related: [{ href: "/canada/creation-site-web", label: "Concevoir un site bilingue pour le Canada" }, { href: "/developpeur-react", label: "Interfaces et API React" }, { href: "/canada/developpeur-web-freelance", label: "Organiser une mission à distance" }],
  },
  "/france/developpeur-nextjs": {
    sections: [
      { title: "Des routes Next.js pour vos contenus publics", paragraphs: ["Pour un site de services ou un catalogue, chaque URL doit répondre à un besoin identifiable. Je vérifie les contenus livrés dans le HTML, les métadonnées de route et les liens qui permettent d’accéder aux pages importantes.", "Une application avec connexion ajoute une autre contrainte : séparer les contenus publics des données propres à un compte. Le choix de cache et de rendu est fait route par route, sans mettre en cache des informations privées par défaut."], items: ["Rendu public", "Métadonnées par route", "Séparation public et privé", "Cache défini selon les données"] },
      { title: "Refonte et déploiement pour votre équipe", paragraphs: ["Une refonte est préparée avec l’inventaire des URLs et des dépendances. L’équipe valide les correspondances entre anciennes et nouvelles pages avant la publication pour préserver les liens utiles.", "La livraison comprend les hypothèses d’hébergement, les variables nécessaires et les vérifications de production. Les mesures de performance sont faites sur les pages prioritaires ; le framework seul ne constitue pas une preuve de vitesse ou de classement."], items: ["Plan de redirections", "Revue des dépendances", "Vérifications de production", "Mesures sur pages représentatives"] },
    ],
    faqs: [{ question: "Pouvez-vous ajouter Next.js à un frontend React existant ?", answer: "Une migration peut être envisagée si le rendu, le routage ou les contenus le justifient. Un audit doit d’abord estimer les modifications, les compatibilités et le bénéfice attendu." }, { question: "Comment préserver les URLs d’une refonte ?", answer: "Nous établissons une correspondance entre les pages existantes et leurs remplacements. Les redirections et les liens internes sont ensuite vérifiés sur le domaine de production." }],
    projectSlugs: [],
    related: [{ href: "/developpeur-nextjs", label: "Rendu et déploiement Next.js" }, { href: "/blog/nextjs-seo-app-router-2026", label: "Comprendre le SEO de l’App Router" }, { href: "/france/developpeur-react", label: "Renfort React en équipe" }],
  },
  "/france/developpeur-php": {
    sections: [
      { title: "Reprendre un site PHP déjà utilisé par vos clients", paragraphs: ["Une reprise commence par les fonctions qui doivent continuer à fonctionner : formulaires, commandes, accès administrateur et échanges de données. Je reproduis les anomalies avant de proposer une correction ou une migration.", "Le cadrage précise l’accès au code, à un environnement de test et à une copie adaptée de la base. Il vérifie aussi la version PHP de l’hébergement, les extensions et les services tiers dont le site dépend."], items: ["Audit de reprise", "PHP et hébergement", "Base MySQL", "Parcours à préserver"] },
      { title: "Un backend lisible pour votre organisation", paragraphs: ["Les évolutions peuvent porter sur un export, un espace de gestion, une validation métier ou une connexion API. Les droits et les formats sont définis avec les utilisateurs concernés afin de ne pas déplacer toute la logique dans le navigateur.", "La boutique PHP et MySQL du portfolio donne un exemple de catalogue et de commande avec paiement à la livraison. Pour votre activité en France, les modes de règlement et la logistique sont cadrés selon votre fonctionnement propre."], items: ["Validations serveur", "Permissions", "Exports et intégrations", "Documentation de reprise"] },
    ],
    faqs: [{ question: "Puis-je conserver mon hébergement PHP ?", answer: "Oui, si ses versions, ses extensions et ses ressources conviennent au projet. La compatibilité est vérifiée avant de définir le déploiement." }, { question: "Comment limiter le risque d’une correction sur un site actif ?", answer: "Les modifications sont préparées dans un environnement de test, avec une sauvegarde et une procédure de retour arrière adaptées. Les parcours concernés sont validés avant publication." }],
    projectSlugs: ["site-ecommerce"],
    related: [{ href: "/developpeur-php", label: "PHP, MySQL et intégrations" }, { href: "/portfolio/site-ecommerce", label: "Exemple de boutique PHP" }, { href: "/maintenance-site-web", label: "Maintenance d’un site existant" }],
  },
  "/belgique/creation-site-web": {
    sections: [
      { title: "Définir les langues et les publics de votre site en Belgique", paragraphs: ["La première décision concerne votre audience réelle : francophone, néerlandophone, anglophone ou plusieurs publics. Le développement peut prévoir des versions distinctes, mais chaque contenu doit être fourni ou validé dans la langue concernée.", "Les menus, les prestations et les formulaires sont organisés pour éviter qu’un visiteur change de langue sans le comprendre. Les zones desservies sont décrites d’après votre activité ; une adresse ou une implantation locale ne doit pas être ajoutée pour le seul référencement."], items: ["Audience et langues", "Textes validés", "Navigation entre versions", "Coordonnées réelles"] },
      { title: "Un site administrable selon votre fréquence de publication", paragraphs: ["Si vous ajoutez régulièrement des actualités, des offres ou des réalisations, une interface de gestion doit être prévue. Si le contenu évolue peu et que le site comporte des fonctions particulières, une autre architecture peut être adaptée.", "Le devis détaille les pages, les fonctions de gestion, l’hébergement et l’accompagnement à la mise à jour. Le travail est réalisé depuis le Maroc avec des validations à distance, sans bureau belge revendiqué."], items: ["CMS ou architecture sur mesure", "Pages et fonctions de gestion", "Livraison des accès", "Maintenance à définir"] },
    ],
    faqs: [{ question: "Pouvez-vous prévoir une version néerlandaise ?", answer: "La structure technique peut l’accueillir. Les traductions doivent être fournies ou validées par une personne compétente dans cette langue ; elles ne sont pas supposées incluses dans le développement." }, { question: "Disposez-vous d’une agence en Belgique ?", answer: "Non. Vous échangez directement avec un développeur freelance basé au Maroc et disponible à distance." }],
    projectSlugs: ["reby-art", "horea-formation"],
    related: [{ href: "/belgique", label: "Organiser une collaboration depuis la Belgique" }, { href: "/creation-site-web", label: "Comparer CMS et développement sur mesure" }],
  },
  "/suisse/creation-site-web": {
    sections: [
      { title: "Cadrer un site pour votre clientèle en Suisse", paragraphs: ["Un site pour une clientèle romande et un site destiné à plusieurs régions linguistiques demandent des contenus différents. Nous définissons les langues utiles à votre activité et les pages disponibles dans chacune avant de dessiner la navigation.", "Les coordonnées, les prestations et les modes de contact sont ceux de votre entreprise. Pour un commerce en ligne, la devise et les territoires de livraison sont explicités ; les intégrations de paiement et de facturation sont examinées séparément."], items: ["Clientèle et langues", "Pages de prestations", "Devise si nécessaire", "Contact et contenus validés"] },
      { title: "Préparer la livraison et la reprise du site", paragraphs: ["Le périmètre précise qui gère le domaine, l’hébergement et les contenus après la mise en ligne. Une recette permet de vérifier les formulaires, les pages mobiles et les liens depuis le domaine final.", "Les fonctions nouvelles sont distinguées du site initial et de sa maintenance. Le développement se fait à distance depuis le Maroc, avec un référent de validation côté client et des points de suivi convenus."], items: ["Recette sur le domaine final", "Propriété des accès", "Prise en main", "Évolutions séparées"] },
    ],
    faqs: [{ question: "Une version allemande ou italienne peut-elle être prévue ?", answer: "Oui pour la structure du site. Les contenus et leur validation doivent être organisés dans chaque langue retenue et précisés au devis." }, { question: "Pouvez-vous utiliser mon hébergement existant ?", answer: "L’hébergement est examiné selon la technologie et les fonctions du site. Il peut être conservé s’il permet un déploiement et une maintenance adaptés." }],
    projectSlugs: ["reby-art", "horea-formation"],
    related: [{ href: "/suisse", label: "Développement à distance pour la Suisse" }, { href: "/creation-site-web", label: "Préparer la structure et les contenus" }],
  },
};

export const marketHubContent: Record<string, LandingPage["sections"]> = {
  belgique: [
    { title: "Choisir les langues avant la technologie", paragraphs: ["Définissez les publics à atteindre et les contenus que votre équipe peut produire en français, en néerlandais ou en anglais. Ces choix déterminent les pages, la navigation et les validations nécessaires.", "Le développement peut couvrir un site de services, un catalogue ou un outil métier. Les traductions et les contraintes de votre activité sont fournies ou validées par votre entreprise."], items: ["Audience et contenus", "Versions linguistiques", "Site ou application", "Validation côté client"] },
    { title: "Collaborer avec un développeur depuis la Belgique", paragraphs: ["Les maquettes, les livraisons et les décisions sont regroupées dans un suivi partagé. Le devis définit les points de validation, les accès remis et les responsabilités après publication.", "La mission est réalisée à distance depuis le Maroc. Vous avez un interlocuteur technique direct ; aucune agence ou adresse belge n’est revendiquée."], items: ["Périmètre écrit", "Revues planifiées", "Livraison des accès", "Maintenance définie"] },
  ],
  suisse: [
    { title: "Un périmètre adapté à vos utilisateurs en Suisse", paragraphs: ["Nous distinguons un site destiné à une clientèle romande d’un produit visant plusieurs langues. Les contenus, les formats et les intégrations sont cadrés à partir des utilisateurs réels de votre activité.", "Pour un outil métier, le travail commence par les tâches, les données et les rôles. Pour un site public, il commence par les services à expliquer et le parcours de prise de contact."], items: ["Publics et langues", "Parcours de contact", "Données et permissions", "Intégrations à inventorier"] },
    { title: "Livraison, autonomie et maintenance", paragraphs: ["La réception précise ce qui doit être testé et qui valide chaque étape. Les accès, la configuration de déploiement et les modalités de mise à jour sont prévus dans la livraison.", "La collaboration est organisée à distance depuis le Maroc. Les fonctionnalités futures et la maintenance sont estimées séparément pour garder un périmètre lisible."], items: ["Critères de réception", "Accès au code", "Prise en main", "Évolutions sur devis"] },
  ],
};
