import Link from "next/link";
import Image from "next/image";
import type { LandingPage } from "../lib/landing-pages";
import { absoluteUrl, whatsappUrl } from "../lib/site";
import { caseStudies } from "../lib/portfolio";
import SiteHeader from "./SiteHeader";
import SiteFooter from "./SiteFooter";

function EnglishHeader(){return <header className="sticky top-0 z-50 border-b border-white/10 bg-black/95"><div className="container flex h-20 items-center justify-between"><Link href="/en" className="text-xl font-black">Soufiane<span className="text-[#ff6b00]">.</span></Link><nav className="flex items-center gap-4 text-sm"><Link href="/en/web-development-services">Services</Link><Link className="hidden sm:block" href="/portfolio">Work</Link><Link href="/contact" className="rounded-full bg-[#ff6b00] px-4 py-2 font-bold">Request a quote</Link></nav></div></header>}
function EnglishFooter(){return <footer className="border-t border-white/10 bg-[#050505]"><div className="container grid gap-8 py-12 md:grid-cols-3"><div><p className="text-xl font-black">Soufiane Boutatss</p><p className="mt-3 text-sm leading-6 text-white/55">Remote freelance web developer for international companies, founders and agencies.</p></div><div><h2 className="text-sm uppercase tracking-wider">Services</h2><nav className="mt-4 grid gap-2 text-sm text-white/55"><Link href="/en/react-developer">React development</Link><Link href="/en/nextjs-developer">Next.js development</Link><Link href="/en/php-developer">PHP development</Link></nav></div><div><h2 className="text-sm uppercase tracking-wider">Contact</h2><Link href="/contact" className="mt-4 inline-block text-[#ff8a3d]">Start a conversation →</Link></div></div></footer>}

export default function InternationalLandingPage({ page }: { page: LandingPage }) {
  const url = absoluteUrl(page.path);
  const crumbs = page.path.split("/").filter(Boolean);
  const jsonLd = [
    { "@context": "https://schema.org", "@type": "Service", name: page.h1, description: page.intro, url, areaServed: page.market, provider: { "@id": `${absoluteUrl()}/#person` }, availableChannel: { "@type": "ServiceChannel", serviceUrl: url, availableLanguage: page.lang === "en" ? ["English", "French"] : ["French", "English"] } },
    { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: page.lang === "en" ? "Home" : "Accueil", item: absoluteUrl() }, ...crumbs.map((crumb, i) => ({ "@type": "ListItem", position: i + 2, name: i === crumbs.length - 1 ? page.h1 : crumb, item: absoluteUrl(`/${crumbs.slice(0, i + 1).join("/")}`) }))] },
    { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: page.faqs.map(f => ({ "@type": "Question", name: f.question, acceptedAnswer: { "@type": "Answer", text: f.answer } })) },
  ];
  const copy = page.lang === "en" ? {
    quote: "Request a tailored estimate", whatsapp: "Discuss on WhatsApp", work: "View selected work", scope: "Services and approach", portfolio: "Selected projects", portfolioText: "Real projects already documented in the portfolio, without fabricated metrics or outcomes.", faq: "Frequently asked questions", related: "Continue exploring", final: "Let’s discuss your project", finalText: "Share your goals, existing setup and priority features to receive a clear, tailored response.", contact: "Start a conversation",
  } : {
    quote: "Demander un devis", whatsapp: "Discuter sur WhatsApp", work: "Voir mes réalisations", scope: "Services et méthode", portfolio: "Des projets réels à consulter", portfolioText: "Des réalisations documentées avec leur contexte, leur solution et leurs technologies, sans chiffres ni résultats inventés.", faq: "Questions fréquentes", related: "Poursuivre votre recherche", final: "Discutons de votre projet", finalText: "Présentez vos objectifs, votre existant et les fonctionnalités prioritaires pour recevoir une réponse claire et personnalisée.", contact: "Obtenir une estimation",
  };
  return <>
    {page.lang === "en" ? <EnglishHeader /> : <SiteHeader />}
    <main className="bg-black text-white" lang={page.lang}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <section className="relative overflow-hidden border-b border-white/10 py-20 md:py-28">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,rgba(255,107,0,.17),transparent_32%),linear-gradient(120deg,transparent_45%,rgba(255,255,255,.025))]" />
        <div className="container relative max-w-6xl">
          <nav aria-label="Breadcrumb" className="mb-8 text-sm text-white/50"><Link href="/" className="hover:text-white">{page.lang === "en" ? "Home" : "Accueil"}</Link><span className="mx-2">/</span><span>{page.market}</span></nav>
          <div className="grid items-end gap-10 lg:grid-cols-[1fr_20rem]">
            <div><p className="mb-5 text-sm font-bold uppercase tracking-[.24em] text-[#ff7a1a]">{page.eyebrow}</p><h1 className="max-w-5xl text-4xl font-black leading-[1.03] md:text-6xl lg:text-7xl">{page.h1}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/67">{page.intro}</p></div>
            <aside className="border-l border-[#ff6b00]/50 pl-6 text-sm leading-6 text-white/55"><strong className="block text-white">{page.market}</strong>{page.currency && <span className="block">{page.lang === "en" ? "Project currency" : "Devise projet"} : {page.currency}</span>}<span className="block">Remote · Français · English</span></aside>
          </div>
          <div className="mt-10 flex flex-wrap gap-3"><Link href="/contact" className="rounded-full bg-[#ff6b00] px-7 py-4 font-bold">{copy.quote}</Link><a target="_blank" rel="noopener noreferrer" href={whatsappUrl(`${page.lang === "en" ? "Hello" : "Bonjour"} Soufiane, ${page.h1}`)} className="rounded-full border border-white/20 px-7 py-4 font-bold hover:border-[#ff6b00]">{copy.whatsapp}</a><Link href="/portfolio" className="px-5 py-4 font-bold text-white/65 hover:text-white">{copy.work} →</Link></div>
        </div>
      </section>

      <section className="container py-18 md:py-24"><p className="section-subtitle !text-left">{copy.scope}</p><div className="mt-8 divide-y divide-white/10 border-y border-white/10">{page.sections.map((section, index) => <section key={section.title} className="grid gap-8 py-12 lg:grid-cols-[.72fr_1.28fr]"><div><span className="text-xs font-black text-[#ff7a1a]">0{index + 1}</span><h2 className="mt-3 text-2xl font-black md:text-4xl">{section.title}</h2></div><div><div className="space-y-4 text-base leading-8 text-white/62">{section.paragraphs.map(p => <p key={p}>{p}</p>)}</div>{section.items && <ul className="mt-7 grid gap-3 sm:grid-cols-2">{section.items.map(item => <li key={item} className="border-l border-white/15 py-1 pl-4 text-sm text-white/75">{item}</li>)}</ul>}<div className="mt-8"><Link href="/contact" className="text-sm font-bold text-[#ff8a3d] hover:text-white">{copy.contact} →</Link></div></div></section>)}</div></section>

      <section className="border-y border-white/10 bg-white/[.025] py-20"><div className="container"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="section-subtitle !text-left">Portfolio</p><h2 className="mt-2 text-3xl font-black md:text-5xl">{copy.portfolio}</h2><p className="mt-4 max-w-2xl text-white/55">{copy.portfolioText}</p></div><Link href="/portfolio" className="font-bold text-[#ff8a3d]">{copy.work} →</Link></div><div className="mt-10 grid gap-6 md:grid-cols-3">{caseStudies.slice(0,3).map((project,index) => {const english=[{title:"Ecommerce website with cash on delivery",category:"Ecommerce",summary:"An online store with product catalogue, ordering flow and cash-on-delivery support."},{title:"Reby Art — Artist portfolio",category:"Portfolio website",summary:"A focused React portfolio designed to showcase a French painter and their work."},{title:"HighUp Counselling — Service website",category:"Professional website",summary:"A Canadian website structured to explain counselling services and support enquiries."}][index]; const shown=page.lang==="en"?{...project,...english}:project; return <article key={project.slug} className="overflow-hidden border border-white/10 bg-black"><div className="relative aspect-video"><Image src={project.image} alt={`${page.lang === "en" ? "Preview of" : "Aperçu de"} ${shown.title}`} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover" /></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-[#ff8a3d]">{shown.category}</p><h3 className="mt-2 text-xl font-bold">{shown.title}</h3><p className="mt-3 text-sm leading-6 text-white/55">{shown.summary}</p><Link href={`/portfolio/${project.slug}`} className="mt-5 inline-block text-sm font-bold">Case study →</Link></div></article>})}</div></div></section>

      <section className="container grid gap-12 py-20 lg:grid-cols-[.7fr_1.3fr]"><div><p className="section-subtitle !text-left">FAQ</p><h2 className="mt-2 text-3xl font-black md:text-5xl">{copy.faq}</h2><div className="mt-8"><Link href="/contact" className="rounded-full bg-[#ff6b00] px-6 py-3 font-bold">{copy.quote}</Link></div></div><div className="divide-y divide-white/10 border-y border-white/10">{page.faqs.map(faq => <details key={faq.question} className="group py-6"><summary className="cursor-pointer list-none pr-8 text-lg font-bold">{faq.question}</summary><p className="mt-4 max-w-3xl leading-7 text-white/60">{faq.answer}</p></details>)}</div></section>

      <section className="container border-t border-white/10 py-12"><h2 className="text-xl font-bold">{copy.related}</h2><nav className="mt-5 flex flex-wrap gap-3" aria-label={copy.related}>{page.related.map(link => <Link key={link.href} href={link.href} className="rounded-full border border-white/12 px-4 py-2 text-sm text-white/65 hover:border-[#ff6b00] hover:text-white">{link.label}</Link>)}</nav></section>
      <section className="border-t border-white/10 bg-[#0a0806] py-20 text-center"><div className="container max-w-3xl"><h2 className="text-4xl font-black md:text-6xl">{copy.final}</h2><p className="mx-auto mt-5 max-w-xl text-white/60">{copy.finalText}</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/contact" className="rounded-full bg-[#ff6b00] px-8 py-4 font-bold">{copy.contact}</Link><a target="_blank" rel="noopener noreferrer" href={whatsappUrl(page.h1)} className="rounded-full border border-white/20 px-8 py-4 font-bold">WhatsApp</a></div></div></section>
    </main>{page.lang === "en" ? <EnglishFooter /> : <SiteFooter />}
  </>;
}
