import type { Metadata } from "next";
import "./globals.css";

import Script from "next/script";

export const metadata: Metadata = {
  title: "soufiane boutatss",
  description: "Generated by create next app",
   icons: {
    icon: [
      { url: "https://portfoliosoufdev.vercel.app/static/media/so.c04a87ed30752959fd17.png" },
    ],
    apple: [
      { url: "https://portfoliosoufdev.vercel.app/static/media/so.c04a87ed30752959fd17.png" },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
         <link rel="apple-touch-icon" href="https://portfoliosoufdev.vercel.app/static/media/so.c04a87ed30752959fd17.png" />
      </head>
      <body className="antialiased">
        <Script
          id="orchids-browser-logs"
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts/orchids-browser-logs.js"
          strategy="afterInteractive"
          data-orchids-project-id="25fe0452-9320-4752-80dd-44fdc2737b22"
        />
       
        <Script
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
          strategy="afterInteractive"
          data-target-origin="*"
          data-message-type="ROUTE_CHANGE"
          data-include-search-params="true"
          data-only-in-iframe="true"
          data-debug="true"
          data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}'
        />
        {children}
      
      </body>
    </html>
  );
}
